apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: back
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
        - name: fastapi-app
          image: gambolkf/inz-back:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
