apiVersion: v1
kind: Service
metadata:
  name: fastapi-app-service
  namespace: back
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001
  selector:
    app: fastapi-app
